
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rswnsghsvtqiqhysdhas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzd25zZ2hzdnRxaXFoeXNkaGFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwODc4NjYsImV4cCI6MjA1OTY2Mzg2Nn0.xjy8suHHV1v2a23HphH96q2_Upr49dIzQjSRoeop-eQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
